export const PRIMARY = "#2ECC71";
export const PRIMARY_DARK = "#27AE60";

export const Colors = {
  light: {
    background: "#F0F5F1",
    card: "#FFFFFF",
    text: "#1A1A1A",
    textSecondary: "#666666",
    textMuted: "#AAAAAA",
    border: "#E8EEE8",
    tint: PRIMARY_DARK,
    icon: "#555555",
    tabIconDefault: "#AAAAAA",
    tabIconSelected: PRIMARY_DARK,
    tabBar: "#FFFFFF",
    tabBarBorder: "#E8E8E8",
    separator: "#F0F0F0",
    switchActive: PRIMARY_DARK,
    badgePassed: "#ECECEC",
    badgePassedText: "#888888",
    badgeNext: PRIMARY_DARK,
    badgeNextText: "#FFFFFF",
    nextCardBorder: PRIMARY_DARK,
    nextCardBg: "#F0FFF4",
    headerTitle: PRIMARY_DARK,
    totalBadgeBg: "#E8F5E9",
    totalBadgeText: PRIMARY_DARK,
    resetBtn: "#F5F5F5",
    resetBtnText: "#555555",
    addBtn: PRIMARY_DARK,
    addBtnText: "#FFFFFF",
    countBox: "#F5F5F5",
    countBoxText: "#1A1A1A",
    settingRow: "#FFFFFF",
    sectionHeader: "#F8FBF8",
    // ── progress / motivation / regret ─────────────────────────────
    progressTrack: "#E6ECE6",
    progressFill: PRIMARY_DARK,
    progressComplete: "#1E9E55",
    success: "#1E9E55",
    successBg: "#E8F7EE",
    successText: "#15803D",
    warn: "#E07A1F",
    warnBg: "#FDF1E4",
    warnText: "#B45309",
    danger: "#E0533A",
    dangerBg: "#FCEDE9",
    dangerText: "#B91C1C",
    cardShadow: "rgba(20, 60, 30, 0.10)",
    overlay: "rgba(0,0,0,0.45)",
    ayatAccent: "#7C5CFC",
    ayatBg: "#F1EEFE",
  },
  dark: {
    background: "#0A130A",
    card: "#162416",
    text: "#ECEDEE",
    textSecondary: "#A0B0A0",
    textMuted: "#6B7B6B",
    border: "#243424",
    tint: PRIMARY,
    icon: "#9BA1A6",
    tabIconDefault: "#546054",
    tabIconSelected: PRIMARY,
    tabBar: "#0F1B0F",
    tabBarBorder: "#1A2C1A",
    separator: "#1A2C1A",
    switchActive: PRIMARY,
    badgePassed: "#1E301E",
    badgePassedText: "#6A9A6A",
    badgeNext: PRIMARY,
    badgeNextText: "#0A130A",
    nextCardBorder: PRIMARY,
    nextCardBg: "#162416",
    headerTitle: PRIMARY,
    totalBadgeBg: "#1B2D1B",
    totalBadgeText: PRIMARY,
    resetBtn: "#1B2D1B",
    resetBtnText: "#A0B0A0",
    addBtn: PRIMARY,
    addBtnText: "#0A130A",
    countBox: "#1E301E",
    countBoxText: "#ECEDEE",
    settingRow: "#162416",
    sectionHeader: "#1B2D1B",
    // ── progress / motivation / regret ─────────────────────────────
    progressTrack: "#21351F",
    progressFill: PRIMARY,
    progressComplete: "#3CE07F",
    success: "#3CE07F",
    successBg: "#13321F",
    successText: "#6FE6A2",
    warn: "#F0A24B",
    warnBg: "#33260F",
    warnText: "#F0B978",
    danger: "#F07259",
    dangerBg: "#331814",
    dangerText: "#F09584",
    cardShadow: "rgba(0, 0, 0, 0.45)",
    overlay: "rgba(0,0,0,0.6)",
    ayatAccent: "#A78BFA",
    ayatBg: "#1C1830",
  },
};
