/**
 * Config plugin: wire the release upload keystore into android/app/build.gradle.
 *
 * Credentials live in the USER-GLOBAL ~/.gradle/gradle.properties (never in
 * the repo) as:
 *   YAQEEN_UPLOAD_STORE_FILE / _STORE_PASSWORD / _KEY_ALIAS / _KEY_PASSWORD
 *
 * Because android/ is regenerated by `expo prebuild`, editing build.gradle
 * by hand would be wiped — this plugin re-applies the signing config on
 * every prebuild. When the properties are absent (e.g. another machine),
 * release builds fall back to the debug keystore so local APK testing
 * keeps working.
 */
const { withAppBuildGradle } = require("@expo/config-plugins");

const RELEASE_SIGNING = `
        release {
            if (project.hasProperty('YAQEEN_UPLOAD_STORE_FILE')) {
                storeFile file(YAQEEN_UPLOAD_STORE_FILE)
                storePassword YAQEEN_UPLOAD_STORE_PASSWORD
                keyAlias YAQEEN_UPLOAD_KEY_ALIAS
                keyPassword YAQEEN_UPLOAD_KEY_PASSWORD
            }
        }`;

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    let s = cfg.modResults.contents;
    if (!s.includes("YAQEEN_UPLOAD_STORE_FILE")) {
      s = s.replace(/signingConfigs\s*\{/, `signingConfigs {${RELEASE_SIGNING}`);
      s = s.replace(
        /(buildTypes\s*\{[\s\S]*?release\s*\{[\s\S]*?)signingConfig signingConfigs\.debug/,
        "$1signingConfig project.hasProperty('YAQEEN_UPLOAD_STORE_FILE') ? signingConfigs.release : signingConfigs.debug",
      );
    }
    cfg.modResults.contents = s;
    return cfg;
  });
};
